chunk_size: 256
local_device: "cpu"
max_local_cache_size: 0.2
remote_url: "lm://192.168.2.27:65432"
# remote_url: "redis://192.168.2.27:6379"
remote_serde: "safetensor"

# Whether retrieve() is pipelined or not
# pipelined_backend: False
